#!/usr/bin/env bash
# fix Ubuntu container's to listen on port 80, debugging nginx port 80
# I solved it this way: I deleted the existing ../sites-enabled/default and replaced it with a copy of
# ../sites-available/default. You do that by creating a symbolic link. 
# NB: The flag -s creates a symbolic link, -f deletes the existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
