#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing the script PID
# displays "To infinity and beyond" infinitely
# displays "I hate the kill command" when receiving a SIGTERM signal
# displays "Y U no love me?!" when receiving a SIGINT signa
# deletes the file and terminates when receiving a SIGQUIT or SIGTERM signal
echo "$$" > /var/run/myscript.pid

terminator() {
  rm /var/run/myscript.pid
  exit
}

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done

clean_up
