#!/usr/bin/env bash
#Bash script that displays Best School 10 times but Hi for the 9th iteration

index=0

while [ $index -lt 10 ]
do
    echo "Best School"
  if [ $index -eq 8 ]
  then
    echo "Hi"
  fi
    ((index++))
done
