#!/usr/bin/env bash
# running Nginx  as nginx user
pkill apache2
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx.conf
chmod 0700 /etc/nginx.conf
service nginx restart
